SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */






/* Create Tables */

CREATE TABLE ADMIN
(
	-- 管理员ID
	ID INT NOT NULL AUTO_INCREMENT COMMENT '管理员ID',
	-- 管理员名称
	NAME VARCHAR(30) NOT NULL COMMENT '管理员名称',
	-- 管理员登陆密码
	PWD VARCHAR(30) NOT NULL COMMENT '管理员登陆密码',
	-- 最近登陆时间
	LATE_TIME DATE COMMENT '最近登陆时间',
	PRIMARY KEY (ID)
);


-- APP  信息表
CREATE TABLE APPITEM
(
	-- app的ID
	-- 
	APP_ID INT NOT NULL AUTO_INCREMENT COMMENT 'app的ID
',
	-- 创建用户的ID
	-- 
	USER_ID INT COMMENT '创建用户的ID
',
	-- APP名称
	NAME VARCHAR(30) NOT NULL COMMENT 'APP名称',
	-- app下载链接
	DOWN_LINK VARCHAR(0) COMMENT 'app下载链接',
	-- APP介绍
	INTRODUCE TEXT NOT NULL COMMENT 'APP介绍',
	-- 创建时间
	CREATETIME DATE COMMENT '创建时间',
	-- app 的展示状态，显示/不显示
	STATE BOOLEAN NOT NULL COMMENT 'app 的展示状态，显示/不显示',
	-- 浏览次数
	COUNT INT DEFAULT 0 NOT NULL COMMENT '浏览次数',
	-- 点赞数
	SUPPORT INT DEFAULT 0 COMMENT '点赞数',
	-- 踩数
	DISLIKE INT DEFAULT 0 COMMENT '踩数',
	PRIMARY KEY (APP_ID)
) COMMENT = 'APP  信息表';


-- APP分类表
CREATE TABLE APPTYPE
(
	-- APP类型ID
	-- 
	TYPE_ID INT NOT NULL AUTO_INCREMENT COMMENT 'APP类型ID
',
	-- 类型名
	-- 
	NAME VARCHAR(50) NOT NULL COMMENT '类型名
',
	-- 类型的父ID
	PARENT_ID INT DEFAULT 0 NOT NULL COMMENT '类型的父ID',
	PRIMARY KEY (TYPE_ID)
) COMMENT = 'APP分类表';


CREATE TABLE APPTYPELIST
(
	-- 记录ID
	ID INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	-- app的ID
	-- 
	APP_ID INT NOT NULL COMMENT 'app的ID
',
	-- APP类型ID
	-- 
	TYPE_ID INT NOT NULL COMMENT 'APP类型ID
',
	PRIMARY KEY (ID)
);


-- 网站访问数据统计表
CREATE TABLE COUNT
(
	-- 访问记录id
	-- 
	ID INT NOT NULL AUTO_INCREMENT COMMENT '访问记录id
',
	-- 访问次数
	COUNT INT DEFAULT 0 NOT NULL COMMENT '访问次数',
	-- 时间
	TIME DATE COMMENT '时间',
	PRIMARY KEY (ID)
) COMMENT = '网站访问数据统计表';


CREATE TABLE KEYWORD
(
	-- 关键字记录ID
	KEY_ID INT NOT NULL AUTO_INCREMENT COMMENT '关键字记录ID',
	-- 关键字名称
	NAME VARBINARY(30) NOT NULL COMMENT '关键字名称',
	-- 描述
	DESCRIPTION VARCHAR(100) COMMENT '描述',
	PRIMARY KEY (KEY_ID)
);


-- 按关键字的收集的APP集合
CREATE TABLE KEYWORDLIST
(
	-- 记录ID
	KEYLIST_ID INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	-- 关键字记录ID
	KEY_ID INT NOT NULL COMMENT '关键字记录ID',
	-- app的ID
	-- 
	APP_ID INT NOT NULL COMMENT 'app的ID
',
	PRIMARY KEY (KEYLIST_ID)
) COMMENT = '按关键字的收集的APP集合';


-- 用户留言表
CREATE TABLE MESSAGE
(
	-- 留言记录ID
	-- 
	ID INT NOT NULL AUTO_INCREMENT COMMENT '留言记录ID
',
	-- 用户ID
	-- 
	USER_ID INT COMMENT '用户ID
',
	-- app的ID
	-- 
	APP_ID INT NOT NULL COMMENT 'app的ID
',
	-- 留言内容
	CONTENT TEXT NOT NULL COMMENT '留言内容',
	-- 创建时间
	-- 
	TIME DATE COMMENT '创建时间
',
	PRIMARY KEY (ID)
) COMMENT = '用户留言表';


-- 用户表
CREATE TABLE USER
(
	-- 用户ID
	-- 
	USER_ID INT NOT NULL AUTO_INCREMENT COMMENT '用户ID
',
	-- 用户名
	USERNAME VARCHAR(30) NOT NULL COMMENT '用户名',
	-- 用户头像地址
	LOGO VARCHAR(0) COMMENT '用户头像地址',
	PASSWORD VARCHAR(40) NOT NULL,
	-- 用户最近登陆时间
	LATE_TIME DATE COMMENT '用户最近登陆时间',
	PRIMARY KEY (USER_ID)
) COMMENT = '用户表';



/* Create Foreign Keys */

ALTER TABLE APPTYPELIST
	ADD FOREIGN KEY (APP_ID)
	REFERENCES APPITEM (APP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE KEYWORDLIST
	ADD FOREIGN KEY (APP_ID)
	REFERENCES APPITEM (APP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (APP_ID)
	REFERENCES APPITEM (APP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE APPTYPELIST
	ADD FOREIGN KEY (TYPE_ID)
	REFERENCES APPTYPE (TYPE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE KEYWORDLIST
	ADD FOREIGN KEY (KEY_ID)
	REFERENCES KEYWORD (KEY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE APPITEM
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



